const lang = {
  en: {
    search: "Search",
    all: "All",
    gaming: "Gaming",
    live: "Live",
    cricket: "Cricket",
    cooking: "Cooking",
    songs: "Songs",
    news: "News",
    movies: "Movies",
    sitcoms: "Sitcoms",
    motivation: "Motivation",
    gadgets: "Gadgets",
    guitar: "Guitar",
    shorts: "Shorts",
    videos: "Videos",
    music: "Music",
    sports: "Sports",
    subscriptons: "Subscriptions",
    "watch later": "Watch Later",
  },
  hindi: {
    search: "खोज",
    all: "सभी",
    gaming: "गेमिंग",
    live: "लाइव",
    cricket: "क्रिकेट",
    cooking: "खाना बनाना",
    songs: "गाने",
    news: "समाचार",
    movies: "चलचित्र",
    sitcoms: "सिटकॉम",
    motivation: "प्रेरणा",
    gadgets: "गैजेट्स",
    guitar: "गिटार",
    shorts: "शॉर्ट्स",
    videos: "वीडियो",
    music: "संगीत",
    sports: "खेल",
    subscriptons: "सदस्यता",
    "watch later": "बाद में देखना",
  },
};

export default lang;
